name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    env:
      GOPROXY: https://proxy.golang.org,direct
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: '**/go.sum'

      - name: Configure Go proxy
        run: |
          go env -w GOPROXY=${GOPROXY}

      - name: Sync modules
        run: |
          go mod download
          go mod verify
          go mod tidy -v

      - name: Build (show many errors)
        run: go build -gcflags=all=-e ./...

      - name: Vet
        run: go vet ./...


