name: publish

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
    paths:
      - 'cmd/**'
      - 'internal/**'
      - 'scripts/**'
      - 'Dockerfile'
      - 'go.mod'
      - 'go.sum'
      - 'images/**'
      - 'supervisord.conf'
      - '.github/workflows/publish.yml'
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
    inputs:
      mode:
        description: 'Build mode'
        required: false
        type: choice
        options: [ full, images-only ]
        default: full

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME_GHCR: ghcr.io/swarmnative/volkit
  IMAGE_NAME_DH: docker.io/swarmnative/volkit
  RCLONE_IMAGE: ${{ vars.RCLONE_IMAGE || 'rclone/rclone:latest' }}

jobs:
  go-ci:
    runs-on: ubuntu-latest
    env:
      GOTOOLCHAIN: auto
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - name: Re-generate go.sum (fresh each run)
        run: |
          set -e
          rm -f go.sum || true
          go clean -modcache
          go env -w GOPROXY=https://proxy.golang.org
          go mod tidy
          go mod download
      - name: Lint (golangci-lint)
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=5m
      - name: Build
        run: go build ./...
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test -v ./...

  build-and-push:
    needs: go-ci
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_dispatch' || (github.event.inputs.mode || '') != 'images-only' }}
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
      COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to Docker Hub (optional)
        if: ${{ env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != '' }}
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Compute tags/labels
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE_NAME_GHCR }}
            ${{ env.IMAGE_NAME_DH }}
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=sha,format=short,enable=${{ github.event_name != 'pull_request' }}
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') || github.ref_name == 'main' }}
            type=raw,value=nightly,enable=${{ github.event_name == 'schedule' }}

      - name: Compute dependency fingerprint (nightly only)
        id: fp
        if: ${{ github.event_name == 'schedule' }}
        run: |
          set -euo pipefail
          get_digest() { docker buildx imagetools inspect "$1" | awk '/Digest:/ {print $2; exit}'; }
          ALPINE_DIGEST=$(get_digest alpine:3.20)
          GOLANG_DIGEST=$(get_digest golang:1.22-alpine)
          RCLONE_DIGEST=$(get_digest "${RCLONE_IMAGE}")
          HAPROXY_VER=$(docker run --rm alpine:3.20 sh -c 'apk update >/dev/null 2>&1; apk info -a haproxy | head -1' | tr -d '\r')
          FP_SRC="alpine=${ALPINE_DIGEST}|golang=${GOLANG_DIGEST}|rclone=${RCLONE_DIGEST}|haproxy=${HAPROXY_VER}"
          FP_SHA=$(printf "%s" "$FP_SRC" | sha256sum | awk '{print $1}')
          echo "source=$FP_SRC" >> $GITHUB_OUTPUT
          echo "sha=$FP_SHA" >> $GITHUB_OUTPUT

      - name: Prepare nightly tags (schedule only)
        id: extratags
        if: ${{ github.event_name == 'schedule' }}
        run: |
          {
            echo "list<<EOF"
            echo "${{ env.IMAGE_NAME_GHCR }}:fp-${{ steps.fp.outputs.sha }}"
            echo "${{ env.IMAGE_NAME_DH }}:fp-${{ steps.fp.outputs.sha }}"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Check existing fingerprint tag (GHCR)
        id: check
        if: ${{ github.event_name == 'schedule' }}
        continue-on-error: true
        run: |
          docker manifest inspect ${{ env.IMAGE_NAME_GHCR }}:fp-${{ steps.fp.outputs.sha }} >/dev/null 2>&1

      - name: Skip if no changes (nightly)
        if: ${{ github.event_name == 'schedule' && steps.check.outcome == 'success' }}
        run: |
          echo "Fingerprint unchanged: ${{ steps.fp.outputs.sha }}. Skipping build."
          exit 0

      - name: Build and Push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ steps.extratags.outputs.list }}
          labels: |
            ${{ steps.meta.outputs.labels }}
            org.swarmnative.dep.fingerprint=${{ steps.fp.outputs.sha }}
            org.swarmnative.dep.source=${{ steps.fp.outputs.source }}
          build-args: |
            RCLONE_IMAGE=${{ env.RCLONE_IMAGE }}

      - name: SBOM (Syft)
        uses: anchore/sbom-action@v0
        with:
          artifact-name: sbom.spdx.json
          format: spdx-json
      - name: Sign image (Cosign)
        if: ${{ github.event_name != 'pull_request' && env.COSIGN_KEY != '' && env.COSIGN_PASSWORD != '' }}
        uses: sigstore/cosign-installer@v3
      - name: Cosign Sign
        if: ${{ github.event_name != 'pull_request' && env.COSIGN_KEY != '' && env.COSIGN_PASSWORD != '' }}
        env:
          COSIGN_PASSWORD: ${{ env.COSIGN_PASSWORD }}
        run: |
          echo "${{ env.COSIGN_KEY }}" > cosign.key
          for t in ${{ steps.meta.outputs.tags }}; do
            cosign sign --key cosign.key "$t" || true
          done

      - name: Create GitHub Release (tags only)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-push-rclone:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: ${{ github.event_name != 'pull_request' && env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != '' }}
        with:
          registry: docker.io
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Determine build context (rclone)
        id: ctx_rclone
        run: |
          set -euo pipefail
          if [ -d ./images/volkit-rclone ]; then
            echo "ctx=./images/volkit-rclone" >> $GITHUB_OUTPUT
          else
            echo "rclone Dockerfile path not found" >&2
            exit 1
          fi

      - name: Compute upstream rclone digest
        id: digest_rclone
        run: |
          set -euo pipefail
          UPSTREAM=$(docker buildx imagetools inspect rclone/rclone:latest | awk '/Digest: sha256/ {print $2; exit}')
          echo "upstream_digest=$UPSTREAM" >> $GITHUB_OUTPUT

      - name: Fetch previous rclone image (GHCR)
        id: prev_rclone
        continue-on-error: true
        run: |
          set -euo pipefail
          IMG=ghcr.io/${{ github.repository_owner }}/volkit-rclone:latest
          docker pull "$IMG" || true
          PREV=$(docker image inspect --format '{{ index .Config.Labels "org.opencontainers.image.base.digest" }}' "$IMG" 2>/dev/null || echo "")
          echo "prev_digest=$PREV" >> $GITHUB_OUTPUT

      - name: Decide whether to build rclone
        id: decide_rclone
        run: |
          if [ "${{ steps.prev_rclone.outputs.prev_digest }}" = "${{ steps.digest_rclone.outputs.upstream_digest }}" ] && [ -n "${{ steps.prev_rclone.outputs.prev_digest }}" ]; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Build and Push rclone (GHCR)
        if: steps.decide_rclone.outputs.changed == 'true'
        uses: docker/build-push-action@v5
        id: build_rclone
        with:
          context: ${{ steps.ctx_rclone.outputs.ctx }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/volkit-rclone:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.description=Rclone image for volkit with allow_other enabled
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.base.digest=${{ steps.digest_rclone.outputs.upstream_digest }}

      - name: Mirror rclone to Docker Hub
        if: ${{ steps.decide_rclone.outputs.changed == 'true' && github.event_name != 'pull_request' && env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != '' }}
        run: |
          set -euo pipefail
          DIGEST=${{ steps.build_rclone.outputs.digest }}
          SRC=ghcr.io/${{ github.repository_owner }}/volkit-rclone@${DIGEST}
          docker buildx imagetools create \
            --tag docker.io/${{ env.DOCKERHUB_USERNAME }}/volkit-rclone:latest \
            "$SRC"

  build-push-volkit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: ${{ github.event_name == 'workflow_dispatch' }}
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: ${{ github.event_name != 'pull_request' && env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != '' }}
        with:
          registry: docker.io
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Compute source digest (volkit)
        id: digest_vs3
        run: |
          set -euo pipefail
          base=.
          files=( "$base/Dockerfile" "$base/scripts/entrypoint.sh" "$base/go.mod" "$base/go.sum" $(cd "$base" && git ls-files internal || true) )
          sha=$(sha256sum "${files[@]}" 2>/dev/null | awk '{print $1}' | sha256sum | awk '{print $1}')
          echo "source_digest=$sha" >> $GITHUB_OUTPUT

      - name: Fetch previous volkit image (GHCR)
        id: prev_vs3
        continue-on-error: true
        run: |
          set -euo pipefail
          IMG=ghcr.io/${{ github.repository_owner }}/volkit:latest
          docker pull "$IMG" || true
          PREV=$(docker image inspect --format '{{ index .Config.Labels "org.opencontainers.image.revision.digest" }}' "$IMG" 2>/dev/null || echo "")
          echo "prev_digest=$PREV" >> $GITHUB_OUTPUT

      - name: Decide whether to build volkit
        id: decide_vs3
        run: |
          if [ "${{ steps.prev_vs3.outputs.prev_digest }}" = "${{ steps.digest_vs3.outputs.source_digest }}" ] && [ -n "${{ steps.prev_vs3.outputs.prev_digest }}" ]; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Build and Push volkit (GHCR)
        if: steps.decide_vs3.outputs.changed == 'true'
        uses: docker/build-push-action@v5
        id: build_vs3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/volkit:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.description=Swarm/Docker S3 volume controller
            org.opencontainers.image.licenses=Apache-2.0
            org.opencontainers.image.revision.digest=${{ steps.digest_vs3.outputs.source_digest }}

      - name: Mirror volkit to Docker Hub
        if: ${{ steps.decide_vs3.outputs.changed == 'true' && github.event_name != 'pull_request' && env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != '' }}
        run: |
          set -euo pipefail
          DIGEST=${{ steps.build_vs3.outputs.digest }}
          SRC=ghcr.io/${{ github.repository_owner }}/volkit@${DIGEST}
          docker buildx imagetools create \
            --tag docker.io/${{ env.DOCKERHUB_USERNAME }}/volkit:latest \
            "$SRC"

